### ISSUE TITLE
Permission denied error

### ISSUE THREAD

**Issue by SalvesTestservices** [modosc/cloudflare-rails#147]
In the logs of my application in production I see these errors:

```
cloudflare-rails: error fetching ip addresses from Cloudflare (Permission denied @ apply2files - /var/deploy/application-production/web_head/releases/20240726080539/tmp/cache/958/040/cloudflare-rails%3Aips_v4), falling back to defaults
```

Is there something I can do to solve this?

**Comment by modosc** [comment]
this is a configuration issue. this gem expects `Rails.cache` to be configured. if you don't explicitly configure it then it defaults to using [file_store](https://guides.rubyonrails.org/caching_with_rails.html#activesupport-cache-filestore). the error you're seeing means you need to configure the store's path correctly because the default configuration directory isn't writable.
