### ISSUE TITLE
Sharing another gem on this topic

### ISSUE THREAD

**Issue by metaskills** [modosc/cloudflare-rails#2]
Hey Jonathan! Thanks so much for writing this gem. It proved very helpful in identifying some issues we were having with using Cloudflare on Rails. In the end, we decided to write our own gem that only fixed `request.remote_ip` and broaden the support to Rails 3.2 to 5.0. Here it is:

https://github.com/customink/actionpack-cloudflare

Would you mind sharing your thoughts on this approach? 
I also linked to your project in our readme. Cheers!

**Comment by modosc** [comment]
hey, thanks for the comments. 

one downside to that approach is that anyone can set the `CF-CONNECTING-IP` header in their browser - you can't truly differentiate between someone hitting your endpoint directly and someone coming through cloudfront. 

also, i seem to remember needing the ip address to work in some rack middleware that ran before rails and at that point `request.remote_ip` wasn't correct. also in general i get tired of having to remind people to only use `.remote_ip` and rack did offer a solution similar to the rails way of whitelisting trusted ip addresses. 

but if it works for you, awesome. i'll add a link to your gem as well. 

also i hadn't actually tested this gem for rails 5 since it came out (only on a pre/beta) and it turned out it didn't work, so by filing this you got me to fix a bug and roll a new release, thanks!

**Comment by modosc** [comment]
oh also i remember needing `x-forwarded-for` to work correctly to get the original ip address, and i think using `CF-Connecting-IP` only gives you the last address in that list.

**Comment by metaskills** [comment]
Thanks for sharing! So far we are seeing good data using only `CF-Connecting-IP`. This [article on Cloudflare headers](https://support.cloudflare.com/hc/en-us/articles/200170986-How-does-CloudFlare-handle-HTTP-Request-headers-) seems to suggest that it is what we want. Either way, the data we are getting back from Google analytics suggests it is, so far.
