### ISSUE TITLE
CF-Connecting-IP Header used?

### ISSUE THREAD

**Issue by tmm1** [modosc/cloudflare-rails#9]
The readme says:

>This code will fetch CloudFlare's current [IPv4](https://www.cloudflare.com/ips-v4) and [IPv6](https://www.cloudflare.com/ips-v6) lists, store them in `Rails.cache`, and add them to `config.cloudflare.ips`. The `CF-Connecting-IP` header will then be trusted only from those ip addresses.

But I don't see that header referenced anywhere in the codebase.

**Comment by modosc** [comment]
the `CF-Connecting-IP` header has an identical value to the first entry in [x-forwarded-for](https://support.cloudflare.com/hc/en-us/articles/200170986-How-does-Cloudflare-handle-HTTP-Request-headers-) which is what i use in this gem because of how rack / rails decide on which ip is the correct remote ip. 

that being said, i'll update the docs to make this clearer, thanks for pointing this out.
